use taskdb;

CREATE TABLE Salary_log(
	emp_id int primary key,
    amount int
);

-- create trigger for salary log to set default values
DELIMITER &&

CREATE TRIGGER salarylog 
BEFORE INSERT ON orders
FOR EACH ROW 
BEGIN
-- IF AMOUNT < 5000 , SET IT TO 5000

IF NEW.amount < 5000 THEN 
SET NEW.amount = 5000;
END IF;

-- SET NEW.CUSTOMERID = ROUND(NEW.CUSTOMERID);

END&&

DELIMITER ;

-- Check Trigger 
INSERT INTO ORDERS(ORDERID,CUSTOMERID,ORDERDATE,AMOUNT) VALUES(105,5,CURDATE(),3000);


-- create trigger for round off value
DELIMITER &&

CREATE TRIGGER salarylog 
BEFORE INSERT ON orders
FOR EACH ROW 
BEGIN
-- IF AMOUNT < 5000 , SET IT TO 5000

-- IF NEW.amount < 5000 THEN 
-- SET NEW.amount = 5000;
-- END IF;

SET NEW.CUSTOMERID = ROUND(NEW.CUSTOMERID);

END&&

DELIMITER ;

-- Check the round 
INSERT INTO ORDERS(ORDERID,CUSTOMERID,ORDERDATE,AMOUNT) VALUES(106,5.64,CURDATE(),3000);


-- trigger creation for date validation
DELIMITER @@

CREATE TRIGGER datevalidation 
BEFORE INSERT ON orders
FOR EACH ROW 
BEGIN
-- IF AMOUNT < 5000 , SET IT TO 5000
IF
NEW.ORDERDATE IS NULL THEN 
SET NEW.ORDERDATE = CURDATE();
END IF ;

END@@

DELIMITER ;

-- check the date validation
INSERT INTO ORDERS(ORDERID,CUSTOMERID,ORDERDATE,AMOUNT) VALUES(107,7,NULL,3000);

