  // ---------- Using let ----------
        let userName = "JohnDoe"; 
        console.log("userName:", userName);
        let regNo = "ICT2025";
        console.log("regNo:", regNo);
        let mobileNo = "9876543210"; 
        console.log("mobileNo:", mobileNo);
        let emailId = "johndoe@example.com"; 
        console.log("emailId:", emailId);
        let dateOfBirth = "2000-05-10"; 
        console.log("dateOfBirth:", dateOfBirth);
        let genderType = "Male"; 
        console.log("genderType:", genderType);
        let addressLine = "123, Main Street"; 
        console.log("addressLine:", addressLine);
        let cityName = "Chennai"; 
        console.log("cityName:", cityName);
        let stateName = "Tamil Nadu"; 
        console.log("stateName:", stateName);
        let countryName = "India"; 
        console.log("countryName:", countryName);
        let postalCode = "600078"; 
        console.log("postalCode:", postalCode);
        let loginId = "john123"; 
        console.log("loginId:", loginId);
        let passwordHash = "a1b2c3d4"; 
        console.log("passwordHash:", passwordHash);
        let profilePicUrl = "https://example.com/profile.jpg"; 
        console.log("profilePicUrl:", profilePicUrl);
        let accountStatus = "Active"; 
        console.log("accountStatus:", accountStatus);
        let createdAt = "2025-08-27"; 
        console.log("createdAt:", createdAt);
        let updatedAt = "2025-08-28"; 
        console.log("updatedAt:", updatedAt);
        let lastLoginTime = "10:30 AM"; 
        console.log("lastLoginTime:", lastLoginTime);
        let userRole = "Admin"; 
        console.log("userRole:", userRole);
        let isActive = true; 
        console.log("isActive:", isActive);
        let employeeId = "EMP102"; 
        console.log("employeeId:", employeeId);
        let departmentName = "IT Department"; 
        console.log("departmentName:", departmentName);
        let designationTitle = "Software Developer"; 
        console.log("designationTitle:", designationTitle);
        let joiningDate = "2023-07-01"; 
        console.log("joiningDate:", joiningDate);
        let salaryAmount = 55000; 
        console.log("salaryAmount:", salaryAmount);
        let bonusAmount = 10000; 
        console.log("bonusAmount:", bonusAmount);
        let bankName = "SBI"; 
        console.log("bankName:", bankName);
        let branchCode = "SBIN00123"; 
        console.log("branchCode:", branchCode);
        let accountNo = "123456789012"; 
        console.log("accountNo:", accountNo);
        let ifscCode = "SBIN000123"; 
        console.log("ifscCode:", ifscCode);
        let panNo = "ABCDE1234F"; 
        console.log("panNo:", panNo);
        let aadhaarNo = "123456789012"; 
        console.log("aadhaarNo:", aadhaarNo);
        let projectId = "PRJ1001"; 
        console.log("projectId:", projectId);
        let projectName = "ERP System"; 
        console.log("projectName:", projectName);
        let projectDeadline = "2025-12-31"; 
        console.log("projectDeadline:", projectDeadline);
        let taskId = "TSK2001"; 
        console.log("taskId:", taskId);
        let taskTitle = "Frontend Development"; 
        console.log("taskTitle:", taskTitle);
        let taskStatus = "In Progress"; 
        console.log("taskStatus:", taskStatus);
        let managerName = "Karthik"; 
        console.log("managerName:", managerName);
        let teamSize = 6; 
        console.log("teamSize:", teamSize);
        let feedbackScore = 4.5; 
        console.log("feedbackScore:", feedbackScore);
        let ratingValue = 5; 
        console.log("ratingValue:", ratingValue);
        let courseId = "CRS101"; 
        console.log("courseId:", courseId);
        let courseTitle = "Data Structures"; 
        console.log("courseTitle:", courseTitle);
        let courseDuration = "3 Months"; 
        console.log("courseDuration:", courseDuration);
        let enrollmentDate = "2025-01-15"; 
        console.log("enrollmentDate:", enrollmentDate);
        let completionDate = "2025-04-15"; 
        console.log("completionDate:", completionDate);
        let certificateUrl = "https://example.com/certificate.pdf"; 
        console.log("certificateUrl:", certificateUrl);

        // ---------- Using var ----------
        var userNameVar = "JaneDoe"; 
        console.log("userNameVar:", userNameVar);
        var regNoVar = "ICT2026"; 
        console.log("regNoVar:", regNoVar);
        var mobileNoVar = "9876501234"; 
        console.log("mobileNoVar:", mobileNoVar);
        var emailIdVar = "janedoe@example.com"; 
        console.log("emailIdVar:", emailIdVar);
        var dateOfBirthVar = "2001-11-20"; 
        console.log("dateOfBirthVar:", dateOfBirthVar);
        var genderTypeVar = "Female"; 
        console.log("genderTypeVar:", genderTypeVar);
        var addressLineVar = "45, North Street"; 
        console.log("addressLineVar:", addressLineVar);
        var cityNameVar = "Trichy"; 
        console.log("cityNameVar:", cityNameVar);
        var stateNameVar = "Tamil Nadu"; 
        console.log("stateNameVar:", stateNameVar);
        var countryNameVar = "India"; 
        console.log("countryNameVar:", countryNameVar);
        var postalCodeVar = "620001"; 
        console.log("postalCodeVar:", postalCodeVar);
        var loginIdVar = "jane123"; 
        console.log("loginIdVar:", loginIdVar);
        var passwordHashVar = "x9y8z7w6"; 
        console.log("passwordHashVar:", passwordHashVar);
        var profilePicUrlVar = "https://example.com/jane.jpg"; 
        console.log("profilePicUrlVar:", profilePicUrlVar);
        var accountStatusVar = "Inactive"; 
        console.log("accountStatusVar:", accountStatusVar);
        var createdAtVar = "2025-08-01"; 
        console.log("createdAtVar:", createdAtVar);
        var updatedAtVar = "2025-08-10"; 
        console.log("updatedAtVar:", updatedAtVar);
        var lastLoginTimeVar = "08:00 PM"; 
        console.log("lastLoginTimeVar:", lastLoginTimeVar);
        var userRoleVar = "User"; 
        console.log("userRoleVar:", userRoleVar);
        var isActiveVar = false; 
        console.log("isActiveVar:", isActiveVar);
        var employeeIdVar = "EMP103"; 
        console.log("employeeIdVar:", employeeIdVar);
        var departmentNameVar = "HR Department"; 
        console.log("departmentNameVar:", departmentNameVar);
        var designationTitleVar = "HR Manager"; 
        console.log("designationTitleVar:", designationTitleVar);
        var joiningDateVar = "2022-06-15"; 
        console.log("joiningDateVar:", joiningDateVar);
        var salaryAmountVar = 65000; 
        console.log("salaryAmountVar:", salaryAmountVar);
        var bonusAmountVar = 8000; 
        console.log("bonusAmountVar:", bonusAmountVar);
        var bankNameVar = "ICICI"; 
        console.log("bankNameVar:", bankNameVar);
        var branchCodeVar = "ICIC00045"; 
        console.log("branchCodeVar:", branchCodeVar);
        var accountNoVar = "654321098765"; 
        console.log("accountNoVar:", accountNoVar);
        var ifscCodeVar = "ICIC000045"; 
        console.log("ifscCodeVar:", ifscCodeVar);
        var panNoVar = "PQRSX6789Z"; 
        console.log("panNoVar:", panNoVar);
        var aadhaarNoVar = "456789123456"; 
        console.log("aadhaarNoVar:", aadhaarNoVar);
        var projectIdVar = "PRJ1002"; 
        console.log("projectIdVar:", projectIdVar);
        var projectNameVar = "CRM Tool"; 
        console.log("projectNameVar:", projectNameVar);
        var projectDeadlineVar = "2026-03-15"; 
        console.log("projectDeadlineVar:", projectDeadlineVar);
        var taskIdVar = "TSK2002"; 
        console.log("taskIdVar:", taskIdVar);
        var taskTitleVar = "Backend Development"; 
        console.log("taskTitleVar:", taskTitleVar);
        var taskStatusVar = "Completed"; 
        console.log("taskStatusVar:", taskStatusVar);
        var managerNameVar = "Arun"; 
        console.log("managerNameVar:", managerNameVar);
        var teamSizeVar = 10; 
        console.log("teamSizeVar:", teamSizeVar);
        var feedbackScoreVar = 4.7; 
        console.log("feedbackScoreVar:", feedbackScoreVar);
        var ratingValueVar = 4; 
        console.log("ratingValueVar:", ratingValueVar);
        var courseIdVar = "CRS102"; 
        console.log("courseIdVar:", courseIdVar);
        var courseTitleVar = "Operating Systems"; 
        console.log("courseTitleVar:", courseTitleVar);
        var courseDurationVar = "4 Months"; 
        console.log("courseDurationVar:", courseDurationVar);
        var enrollmentDateVar = "2025-02-01"; 
        console.log("enrollmentDateVar:", enrollmentDateVar);
        var completionDateVar = "2025-06-01"; 
        console.log("completionDateVar:", completionDateVar);
        var certificateUrlVar = "https://example.com/os.pdf"; 
        console.log("certificateUrlVar:", certificateUrlVar);

        // ---------- Using const ----------
        const userNameConst = "MikeRoss"; 
        console.log("userNameConst:", userNameConst);
        const regNoConst = "ICT2027"; 
        console.log("regNoConst:", regNoConst);
        const mobileNoConst = "9123456780"; 
        console.log("mobileNoConst:", mobileNoConst);
        const emailIdConst = "mikeross@example.com"; 
        console.log("emailIdConst:", emailIdConst);
        const dateOfBirthConst = "1999-02-15"; 
        console.log("dateOfBirthConst:", dateOfBirthConst);
        const genderTypeConst = "Male"; 
        console.log("genderTypeConst:", genderTypeConst);
        const addressLineConst = "67, Park Avenue"; 
        console.log("addressLineConst:", addressLineConst);
        const cityNameConst = "Bangalore"; 
        console.log("cityNameConst:", cityNameConst);
        const stateNameConst = "Karnataka"; 
        console.log("stateNameConst:", stateNameConst);
        const countryNameConst = "India"; 
        console.log("countryNameConst:", countryNameConst);
        const postalCodeConst = "560001"; 
        console.log("postalCodeConst:", postalCodeConst);
        const loginIdConst = "mike123"; 
        console.log("loginIdConst:", loginIdConst);
        const passwordHashConst = "q1w2e3r4"; 
        console.log("passwordHashConst:", passwordHashConst);
        const profilePicUrlConst = "https://example.com/mike.jpg"; 
        console.log("profilePicUrlConst:", profilePicUrlConst);
        const accountStatusConst = "Active"; 
        console.log("accountStatusConst:", accountStatusConst);
        const createdAtConst = "2025-05-10"; 
        console.log("createdAtConst:", createdAtConst);
        const updatedAtConst = "2025-07-22"; 
        console.log("updatedAtConst:", updatedAtConst);
        const lastLoginTimeConst = "09:15 AM"; 
        console.log("lastLoginTimeConst:", lastLoginTimeConst);
        const userRoleConst = "Manager"; 
        console.log("userRoleConst:", userRoleConst);
        const isActiveConst = true; 
        console.log("isActiveConst:", isActiveConst);
        const employeeIdConst = "EMP104"; 
        console.log("employeeIdConst:", employeeIdConst);
        const departmentNameConst = "Finance Department"; 
        console.log("departmentNameConst:", departmentNameConst);
        const designationTitleConst = "Finance Analyst"; 
        console.log("designationTitleConst:", designationTitleConst);
        const joiningDateConst = "2021-05-20"; 
        console.log("joiningDateConst:", joiningDateConst);
        const salaryAmountConst = 70000; 
        console.log("salaryAmountConst:", salaryAmountConst);
        const bonusAmountConst = 12000; 
        console.log("bonusAmountConst:", bonusAmountConst);
        const bankNameConst = "HDFC"; 
        console.log("bankNameConst:", bankNameConst);
        const branchCodeConst = "HDFC00056"; 
        console.log("branchCodeConst:", branchCodeConst);
        const accountNoConst = "098765432109"; 
        console.log("accountNoConst:", accountNoConst);
        const ifscCodeConst = "HDFC000056"; 
        console.log("ifscCodeConst:", ifscCodeConst);
        const panNoConst = "LMNOP1234Q"; 
        console.log("panNoConst:", panNoConst);
        const aadhaarNoConst = "789456123012"; 
        console.log("aadhaarNoConst:", aadhaarNoConst);
        const projectIdConst = "PRJ1003"; 
        console.log("projectIdConst:", projectIdConst);
        const projectNameConst = "AI Assistant"; 
        console.log("projectNameConst:", projectNameConst);
        const projectDeadlineConst = "2026-06-30"; 
        console.log("projectDeadlineConst:", projectDeadlineConst);
        const taskIdConst = "TSK2003"; 
        console.log("taskIdConst:", taskIdConst);
        const taskTitleConst = "Machine Learning Model"; 
        console.log("taskTitleConst:", taskTitleConst);
        const taskStatusConst = "Ongoing"; 
        console.log("taskStatusConst:", taskStatusConst);
        const managerNameConst = "Suresh"; 
        console.log("managerNameConst:", managerNameConst);
        const teamSizeConst = 8; 
        console.log("teamSizeConst:", teamSizeConst);
        const feedbackScoreConst = 4.9; 
        console.log("feedbackScoreConst:", feedbackScoreConst);
        const ratingValueConst = 5; 
        console.log("ratingValueConst:", ratingValueConst);
        const courseIdConst = "CRS103"; 
        console.log("courseIdConst:", courseIdConst);
        const courseTitleConst = "Machine Learning"; 
        console.log("courseTitleConst:", courseTitleConst);
        const courseDurationConst = "6 Months"; 
        console.log("courseDurationConst:", courseDurationConst);
        const enrollmentDateConst = "2025-03-01"; 
        console.log("enrollmentDateConst:", enrollmentDateConst);
        const completionDateConst = "2025-09-01"; 
        console.log("completionDateConst:", completionDateConst);
        const certificateUrlConst = "https://example.com/ml.pdf"; 
        console.log("certificateUrlConst:", certificateUrlConst);